sprint_20
TheABCDEngineer/PlaylistMarket pull request #24
Opened 2023-05-30 21:00 UTC by TheABCDEngineer

2023-06-02 10:09 UTC, NoDopezzz requested changes

2023-06-02 10:09 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmarket/features/search/data/network/NetworkClientImpIRetrofit.kt
> +                response.apply { responseCode = 200 }
⏫ Не стоит вручную изменять код ответа. Ведь в случае, если запрос отработал успешно, но из-за ошибки нам пришел ответ с кодом например `401`, то мы должны сообщить пользователю об ошибке.
То же касается и ошибок клиента (которые словятся в `catch`). Нельзя их насильно кастить в успешный запрос с кодом **400**, т.к. это усложнит дальнеший процесс отладки. Код **400** означает **Bad Request** - когда мы на бек отправляем например body с синтаксической ошибкой.

Вообще если интересно помонипулировать приходящими и исходящими данными можно воспользоваться [`Interceptor`](https://square.github.io/okhttp/features/interceptors/), подключемые к `HttpClient`'ам.

2023-06-02 10:09 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmarket/features/search/data/TracksRepositoryImplNetwork.kt
> +    override fun searchTracks(expression: String): Flow<ResponseModel> = flow {
⚠️ Так как запрос в сеть предполагает однаразовую операцию - отправили операцию - ждем ответ - отобразили ответ, нам нет необходимости держать `Flow`.
В данном случае более подходящим решением было бы изменить метод `searchTracks` на `suspend`

2023-06-09 16:35 UTC, TheABCDEngineer commented on app/src/main/java/com/example/playlistmarket/di/NetworkModule.kt
> +        NetworkClientImpIRetrofit(get())
Это очень крутая Фитча!!!
А как быть с классами, где в конструкторе аргументы (которые не get)?

2023-06-11 07:52 UTC, NoDopezzz commented on app/src/main/java/com/example/playlistmarket/di/NetworkModule.kt
> +        NetworkClientImpIRetrofit(get())
Их к сожалению, все еще приходится добавлять вручную

2023-06-11 07:52 UTC, NoDopezzz approved these changes

2023-06-16 13:29 UTC, merged